// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>


using namespace cppally;
using internal::cpp_to_sexp;
using internal::dispatch_template_impl;

// doubles.cpp
r_vec<r_lgl> cpp_double_equal(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> tolerance);
extern "C" SEXP _cppdoubles_cpp_double_equal(SEXP x, SEXP y, SEXP tolerance) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_equal(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(tolerance)));
  END_CPPALLY
}
// doubles.cpp
r_vec<r_lgl> cpp_double_gt(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> tolerance);
extern "C" SEXP _cppdoubles_cpp_double_gt(SEXP x, SEXP y, SEXP tolerance) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_gt(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(tolerance)));
  END_CPPALLY
}
// doubles.cpp
r_vec<r_lgl> cpp_double_gte(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> tolerance);
extern "C" SEXP _cppdoubles_cpp_double_gte(SEXP x, SEXP y, SEXP tolerance) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_gte(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(tolerance)));
  END_CPPALLY
}
// doubles.cpp
r_vec<r_lgl> cpp_double_lt(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> tolerance);
extern "C" SEXP _cppdoubles_cpp_double_lt(SEXP x, SEXP y, SEXP tolerance) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_lt(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(tolerance)));
  END_CPPALLY
}
// doubles.cpp
r_vec<r_lgl> cpp_double_lte(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> tolerance);
extern "C" SEXP _cppdoubles_cpp_double_lte(SEXP x, SEXP y, SEXP tolerance) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_lte(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(tolerance)));
  END_CPPALLY
}
// doubles.cpp
r_vec<r_dbl> cpp_double_rel_diff(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> scale);
extern "C" SEXP _cppdoubles_cpp_double_rel_diff(SEXP x, SEXP y, SEXP scale) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_rel_diff(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(scale)));
  END_CPPALLY
}
// doubles.cpp
r_lgl cpp_double_all_equal(r_vec<r_dbl> x, r_vec<r_dbl> y, r_vec<r_dbl> tolerance, r_lgl na_rm);
extern "C" SEXP _cppdoubles_cpp_double_all_equal(SEXP x, SEXP y, SEXP tolerance, SEXP na_rm) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_double_all_equal(as<r_vec<r_dbl>>(x), as<r_vec<r_dbl>>(y), as<r_vec<r_dbl>>(tolerance), as<r_lgl>(na_rm)));
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cppdoubles_cpp_double_all_equal", (DL_FUNC) &_cppdoubles_cpp_double_all_equal, 4},
    {"_cppdoubles_cpp_double_equal",     (DL_FUNC) &_cppdoubles_cpp_double_equal,     3},
    {"_cppdoubles_cpp_double_gt",        (DL_FUNC) &_cppdoubles_cpp_double_gt,        3},
    {"_cppdoubles_cpp_double_gte",       (DL_FUNC) &_cppdoubles_cpp_double_gte,       3},
    {"_cppdoubles_cpp_double_lt",        (DL_FUNC) &_cppdoubles_cpp_double_lt,        3},
    {"_cppdoubles_cpp_double_lte",       (DL_FUNC) &_cppdoubles_cpp_double_lte,       3},
    {"_cppdoubles_cpp_double_rel_diff",  (DL_FUNC) &_cppdoubles_cpp_double_rel_diff,  3},
    {NULL, NULL, 0}
};
}


extern "C" attribute_visible void R_init_cppdoubles(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
