# Generated by cpp11: do not edit by hand

cpp_double_equal <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_equal`, x, y, tolerance)
}

cpp_double_gt <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_gt`, x, y, tolerance)
}

cpp_double_gte <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_gte`, x, y, tolerance)
}

cpp_double_lt <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_lt`, x, y, tolerance)
}

cpp_double_lte <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_lte`, x, y, tolerance)
}

cpp_double_rel_diff <- function(x, y, scale) {
  .Call(`_cppdoubles_cpp_double_rel_diff`, x, y, scale)
}

cpp_double_all_equal <- function(x, y, tolerance, na_rm) {
  .Call(`_cppdoubles_cpp_double_all_equal`, x, y, tolerance, na_rm)
}
