# Generated by cpp11: do not edit by hand

cpp_double_equal_vectorised <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_equal_vectorised`, x, y, tolerance)
}

cpp_double_gt_vectorised <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_gt_vectorised`, x, y, tolerance)
}

cpp_double_gte_vectorised <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_gte_vectorised`, x, y, tolerance)
}

cpp_double_lt_vectorised <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_lt_vectorised`, x, y, tolerance)
}

cpp_double_lte_vectorised <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_lte_vectorised`, x, y, tolerance)
}

cpp_double_rel_diff_vectorised <- function(x, y) {
  .Call(`_cppdoubles_cpp_double_rel_diff_vectorised`, x, y)
}
