# Generated by cppally: do not edit by hand

set_cppdoubles_threads <- function(n) {
  invisible(.Call(`_cppdoubles_set_cppdoubles_threads`, n))
}

get_cppdoubles_threads <- function() {
  .Call(`_cppdoubles_get_cppdoubles_threads`)
}

cpp_double_equal <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_equal`, x, y, tolerance)
}

cpp_double_gt <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_gt`, x, y, tolerance)
}

cpp_double_gte <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_gte`, x, y, tolerance)
}

cpp_double_lt <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_lt`, x, y, tolerance)
}

cpp_double_lte <- function(x, y, tolerance) {
  .Call(`_cppdoubles_cpp_double_lte`, x, y, tolerance)
}

cpp_double_rel_diff <- function(x, y, scale) {
  .Call(`_cppdoubles_cpp_double_rel_diff`, x, y, scale)
}

cpp_double_abs_diff <- function(x, y) {
  .Call(`_cppdoubles_cpp_double_abs_diff`, x, y)
}

cpp_double_all_equal <- function(x, y, tolerance, na_rm) {
  .Call(`_cppdoubles_cpp_double_all_equal`, x, y, tolerance, na_rm)
}
