# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_double_equal_vectorised <- function(x, y, tolerance) {
    .Call(`_cppdoubles_cpp_double_equal_vectorised`, x, y, tolerance)
}

cpp_double_gt_vectorised <- function(x, y, tolerance) {
    .Call(`_cppdoubles_cpp_double_gt_vectorised`, x, y, tolerance)
}

cpp_double_gte_vectorised <- function(x, y, tolerance) {
    .Call(`_cppdoubles_cpp_double_gte_vectorised`, x, y, tolerance)
}

cpp_double_lt_vectorised <- function(x, y, tolerance) {
    .Call(`_cppdoubles_cpp_double_lt_vectorised`, x, y, tolerance)
}

cpp_double_lte_vectorised <- function(x, y, tolerance) {
    .Call(`_cppdoubles_cpp_double_lte_vectorised`, x, y, tolerance)
}

